@startuml
class Usuario {
    +Integer idUsuario
    +String nombre
    +String email
    +String rol
}

' Clase Producto
class Producto {
    +Integer idProducto
    +String nombre
    +Double precio
    +String categoria
}

' Clase Inventario
class Inventario {
    +Integer idInventario
    +Integer cantidad
    +Producto producto
}

' Clase Factura
class Factura {
    +Integer idFactura
    +Date fecha
    +Double total
    +Usuario usuario
}

' Clase DetalleFactura
class DetalleFactura {
    +Integer idDetalle
    +Integer cantidad
    +Double subtotal
    +Factura factura
    +Producto producto
}

' Relaciones entre clases
Usuario  --  Factura : crea
Factura  --  DetalleFactura : tiene
Producto  --  Inventario : esta en
Inventario  --  Producto : controla
Producto  --  DetalleFactura : va
@enduml
